# Site settings
site: Asmosi
title: Asmosi - My personal words
keywords: asmosi, blog
description: >-
  Asmosi - My personal words
lang: en-US
timezone:  Europe/Brussels
# repo: https://github.com/onepase/Ephesus # site repo [optional]
google_verify: # Put your Google Verification here
google_analytics: # Put your Google Analytics code
discus-identifier:  

# Author settings
author:
  name: Andy
  bio: # Bio
  picture: assets/images/profile.jpg 
  github: # github username
  twitter: # twitter username
  facebook: # facebook username
  instagram: # instagram username
  youtube: # youtube username
  linkedin: # linkedin username
  email: # email adress


# URL settings
url: "https://asmosi.be" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false